import json

from services.featherless_client import ask_ai
from models.ai_response import PlanningResponse, PlanStep


def create_plan(memory, context, decision):

    system_prompt = """
You are NEXORA's Planning Agent.

Your job is to create a practical action plan based ONLY on:
1. User memory
2. Context analysis
3. The decision generated by NEXORA

IMPORTANT GROUNDING RULES:

- Never present an AI assumption as a user fact.
- Do not claim the user has a specific skill, weakness, event,
  commitment, resource, schedule, or preference unless it appears
  in the provided memory, context, or decision.
- You MAY recommend specific activities when they are reasonable
  actions toward the selected decision.
- Recommended activities are AI-generated recommendations,
  not user facts.
  - Tasks may contain specific recommended topics or activities,
  but they must be presented as recommendations rather than
  claims about the user's existing knowledge or history.
- When a recommendation uses an external resource or platform,
  treat it as an optional recommendation, not an existing user resource.
- Do not invent appointments, available hours, courses,
  subscriptions, budgets, tools, or personal commitments.
- Do not invent deadlines.
- If a deadline exists, respect it.
- The plan duration must not extend beyond the relevant deadline.
- Keep the plan focused on the selected decision.
- Prefer simple, achievable steps.

Return ONLY valid JSON.

Use EXACTLY this structure:

{
    "goal": "",
    "duration": "",
    "priority": "",
    "steps": [
        {
            "day": "",
            "task": "",
            "reason": ""
        }
    ]
}

IMPORTANT OUTPUT RULES:

- goal must describe the actual goal being addressed.
- duration must be consistent with the user's known deadline
  or the planning horizon selected by the decision.
- priority must be HIGH, MEDIUM, or LOW.
- steps must be an array of objects.
- Every step must contain day, task, and reason.
- Do not add additional fields.
- Do not repeat JSON keys.
- Do not use markdown.
- Do not use ```json.
- Return complete valid JSON only.
"""

    user_prompt = f"""
USER MEMORY:

{json.dumps(memory, indent=2)}

CONTEXT:

{json.dumps(context, indent=2)}

DECISION:

{json.dumps(decision, indent=2)}

Create the action plan using only the information above.
"""

    response = ask_ai(system_prompt, user_prompt)

    response = response.strip()

    if response.startswith("```"):
        response = response.replace("```json", "")
        response = response.replace("```", "")
        response = response.strip()

    try:
        result = json.loads(response)

        required_fields = [
            "goal",
            "duration",
            "priority",
            "steps"
        ]

        for field in required_fields:
            if field not in result:
                raise ValueError(f"Missing field: {field}")

        if result["priority"] not in ["HIGH", "MEDIUM", "LOW"]:
            raise ValueError("Invalid priority")

        if not isinstance(result["steps"], list):
            raise ValueError("steps must be an array")

        for step in result["steps"]:
            for field in ["day", "task", "reason"]:
                if field not in step:
                    raise ValueError(f"Missing step field: {field}")

        return PlanningResponse(
            goal=result["goal"],
            duration=result["duration"],
            priority=result["priority"],
            steps=[
                PlanStep(
                    day=step["day"],
                    task=step["task"],
                    reason=step["reason"]
                )
                for step in result["steps"]
            ]
        )

    except (json.JSONDecodeError, ValueError) as error:
        return {
            "error": "Invalid planning JSON",
            "details": str(error),
            "raw_response": response
        }